# # Network Config
- keyboard_config:
  - write_in:
    - /etc/default/keyboard
    - |
      XKBMODEL="pc105"
      XKBLAYOUT="$${layout}"
      XKBVARIANT=""
      XKBOPTIONS=""
  - exec_in: apt-get -y --force-yes install console-setup console-data 2>&1
