language: nix

sudo: true

branches:
  only:
  - master

services:
  - docker

before_install:
 - nix --version
 - docker --version

install:
 - nix-env -iA cachix -f https://cachix.org/api/v1/install
 - cachix use batsim

script:
 # build docker container and load it into docker
 - nix-build -A batsim-docker-master 'https://github.com/oar-team/nur-kapack/archive/master.tar.gz' -o ./tarball
 - docker load -i ./tarball
 # test that the container works correctly
 - docker run oarteam/batsim:latest --version
 # - nix-env -iA batsched-master batexpe-master -f 'https://github.com/oar-team/nur-kapack/archive/master.tar.gz'
 # - robin --output-dir=./instance --schedcmd=batsched --batcmd="docker run --net host -u $(id -u):$(id -g) -v ${PWD}:/data oarteam/batsim:latest -p '/data/platforms/cluster512.xml' -w '/data/workloads/test_batsim_paper_workload_seed1.json' --mmax-workload -e '/data/instance/out'"
 # - wc -l ./instance/out_jobs.csv
 # push container on dockerhub
 - echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_LOGIN}" --password-stdin
 - docker push oarteam/batsim:latest
