@startmindmap
*[#orange] Tunning
** Topology
*** degree (d) = 4
**** Mesh
**** Torus
**** Random
***** raw
****** in-order 
****** comm-aware
******* stride (s) = 1
******* s = 4
***** aspl-opt
***** bisec-opt
*** d = 6
*** d = 8
** MPI
*** ompi
*** mpich
*** mvapich2
**[#OrangeRed] Collective
*** all-to-all
**** bruck 
**** pair 
**** ring
*** all-gather
**** linear 
**** binomial-tree
*** all-reduce
**** linear
**** binomial-tree
**** flat-tree
**** scatter-gather
@endmindmap
