# Software Install
- enable_contrib: true
- enable_nonfree: true
- enable_backports: true
- enable_lighten: false

- configure_source_list:
  - write_in:
    - /etc/apt/sources.list
    - |
      deb $${apt_repository} $${release} main
      deb-src $${apt_repository} $${release} main
            
      deb http://security.debian.org/ $${release}/updates main
      deb-src http://security.debian.org/ $${release}/updates main

- add_backports:
  - exec_in: |
      if [ $${enable_backports} = true ]; then
        echo "deb $${apt_repository} $${release}-backports main" >> /etc/apt/sources.list
        echo "deb-src $${apt_repository} $${release}-backports main" >> /etc/apt/sources.list
      fi

- add_contribs_and_nonfree_sources:
  - exec_in: |
      if [ $${enable_contrib} = true ]; then
        REPO_CONTRIB="contrib"
      fi
  - exec_in: |
      if [ $${enable_nonfree} = true ]; then
        REPO_NONFREE="non-free"
      fi
  - exec_in: perl -pi -e "s/main$/main $REPO_CONTRIB $REPO_NONFREE/" /etc/apt/sources.list

- update_repositories:
  # Deactivate the check to make the cache system works after a while...
  - exec_in: apt-get -o Acquire::Check-Valid-Until=false -y --force-yes update

- lighten_packages:
  - exec_in: |
      if [ $${enable_lighten} = true ]; then
        mkdir -p /etc/dpkg/dpkg.conf.d
        echo 'path-exclude=/usr/share/locale/*' >> /etc/dpkg/dpkg.conf.d/01_lighten
        echo 'path-exclude=/usr/share/man/*' >> /etc/dpkg/dpkg.conf.d/01_lighten
        echo 'path-exclude=/usr/share/doc/*' >> /etc/dpkg/dpkg.conf.d/01_lighten
        mkdir -p /etc/apt/apt.conf.d
        echo 'APT::Install-Recommends "0" ; APT::Install-Suggests "0" ; ' > /etc/apt/apt.conf.d/01_lighten
      fi
